<?php ?>
<?php if(isset($this->result['errors'])):?>
	<div class="alert alert-danger mt-3" role="alert">
		<?= $this->result['errors']?>
	</div>
<?php endif;?>
<form method="post" action="/auth">
	<div class="form-group">
		<label for="InputLogin">Логин</label>
		<input name="login" required type="text" class="form-control" id="InputLogin" aria-describedby="loginHelp"
		       placeholder="Введите логин">
		<small id="InputLogin" class="form-text text-muted">Сохраняйте, пожалуйста ваш логин и пароль в надёжном
			месте.</small>
	</div>
	<div class="form-group">
		<label for="InputPassword1">Пароль</label>
		<input name="password" required type="password" class="form-control" id="InputPassword1" placeholder="Введите пароль">
	</div>
	<button type="submit" class="btn btn-primary">Вход</button>
</form>

