<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Test PHP Blog application without framework</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<link media="screen" rel="stylesheet" type="text/css"
	      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<link media="screen" rel="stylesheet" type="text/css"
	      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/fontawesome.min.css">
	<link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
	<link href="/css/style_nav.css" media="screen" rel="stylesheet" type="text/css">
	<link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
	<script
		src="https://code.jquery.com/jquery-3.5.0.min.js"
		integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
		crossorigin="anonymous"></script>
	<script src="/js/app.js"></script>


</head>
<body>

<div id="task-container" class="container">
		<?= $this->content; ?>
</div>
<footer>

</footer>
</body>
</html>
